### ISSUE TITLE
Does not remember what.cd session causing it to ask credentials

### ISSUE THREAD

**Issue by bartkl** [YetAnotherNerd/whatlastgenre#10]
Hi,

Love the project, many thanks! There's a (big) nuisance though for me however. Whenever I enter my what.cd credentials (which is done interactively), it stores them neatly but after some time it asks me for those again. Due to this interactivity I can't invoke whatlastgenre in an automated script.

Is this expected behaviour? More importantly, can I do something about this?

Thank you!

**Comment by YetAnotherNerd** [comment]
the idea was to not store the credentials in the config file but ask for them interactively and just store the session cookie to improve security, which got implemented here bf6471e2498b82b0a07b8eb2179812575c89f06e
however, it seems the session cookie is not very long-lasting
the following commit will re-enable optional config values for username/password

**Comment by bartkl** [comment]
I understand, good precaution! But indeed, the session tokens expire quickly, so an option to store credentials would be great.

Thanks again

**Comment by YetAnotherNerd** [comment]
just `git pull` to get the latest code
