### ISSUE TITLE
Discogs API error: 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by jones1008** [YetAnotherNerd/whatlastgenre#13]
I installed wlg according to it's docs and wanted to use it with the Discogs API but it always gives me a 401 error when running whatlastgenre like that:
```bash
./whatlastgenre -vvn /root/Music/
```
Error:
```
/root/Music/Axwell Λ Ingrosso/More Than You Know
[...]
Discogs  album  error: status code 401: UNAUTHORIZED
[...]
```
My configuration is pretty basic
```
[wlg]
sources = mbrainz, lastfm, discogs
whitelist =
tagsfile =
vaqueries = true
id3v23sep =
[genres]
love =
hate =
[scores]
artist = 1.33
various = 0.66
splitup = 0.33
minimum = 0.10
src_discogs = 1.00
src_lastfm = 0.66
src_mbrainz = 0.66
src_redacted = 1.50
[discogs]
token = <consumer-key>
secret = <consumer-secret>
[redacted]
username =
password =
session =
```

Here is the screenshot of how I configured the Discogs API application (censored of course):

![grafik](https://user-images.githubusercontent.com/25104859/38549257-eeadf368-3cb3-11e8-8523-65ec5c679c79.png)

In the config file I took...

- as the `token` the `Consumer-Key` from my API application

- as the `secret` the `Consumer-Secret` from the API application

What am I doing wrong?

**Comment by jones1008** [comment]
A quick testing command from the Discogs API Documentation works:
```bash
curl "https://api.discogs.com/database/search?q=Nirvana" -H "Authorization: Discogs key=<consumer-key>, secret=<consumer-secret>"
```
So authorization in general should work with the provided `token` and `secret`.

**Comment by YetAnotherNerd** [comment]
you don't need to add whatlastgenre as application in your discogs settings and you also don't need to configure the token/secret manually.
just remove the [discogs] section from the config file and rerun wlg, you should be given an url to discogs where you can authorize wlg by logging in and copy&pasting the verification code to the wlg cmdline, the token/secret will be stored in the config automatically.

**Comment by jones1008** [comment]
Wow! this is actually surprisingly easy, once you know how it work.
Now I also understand what this line means in the documentation:

> Authentication information for discogs, will be set interactively.

Thanks for your support.
