### ISSUE TITLE
Allow hard constraints on genres

### ISSUE THREAD

**Issue by tzok** [YetAnotherNerd/whatlastgenre#17]
I have patched the code minimally by setting the `hate` coefficient to zero. Effectively, when I write some tag in the `hate` list I am 100% certain that it will not be used, so this is a hard constraint.

I would like to have one of the two features available:
- Either there is a boolean switch between soft and hard constraints. In the background, this is translated to `love` and `hate` coefficients being either `2.0` and `0.5` or `float('+inf')` and `0.0` respectively
- The `love` and `hate` coefficients are exposed in the config file to set my own values

**Comment by YetAnotherNerd** [comment]
you could remove the tag from the whitelist instead of using a `0.0` hate coefficient.
