### ISSUE TITLE
Tags count/weights

### ISSUE THREAD

**Issue by sekisushai** [YetAnotherNerd/whatlastgenre#18]
I have two questions about the weights for the album and artist tags:

- is it possible to completely ignore the artist's tags for the final score? I tried by putting the following config option
```
[scores]
artist = 0
```
But it doesn't seem to be working. For instance, if the album has only 2 tags and I don't explicitly specify the option `-l 2` when running `whatlastgenre` command, the final result will contain 2 additional tags from the artist to get 4 tags, which is the default option.

- is it possible to take into account the tag counter for the album tags. For instance, if a tag is voted several times by users it should have a higher score. Currently all tags for the album seem to have the same weighting.

Thank you.

**Comment by YetAnotherNerd** [comment]
I addressed your first point by several commits. Using a 0 artist/various score multiplier is supported now (and results in artist queries not being done in first place).

The second points depends on the datasource. discogs and redacted album results don't provide counts/votes, but lastfm and mbrainz should do.
