### ISSUE TITLE
Project state & collaboration ideas

### ISSUE THREAD

**Issue by JOJ0** [YetAnotherNerd/whatlastgenre#36]
Hi @YetAnotherNerd,
it seems this repo is abandonend. I think it's a wonderful addition to beets but I just realised that there is a bug with "Various Artists" releases that is only happening when run as a beets plugin. I'll report later but first I'd like to ask:

Do you plan to continue maintenance or are you gone for good? I'd really like to keep using this software and I started to investigate/debug my issues. I'd like to know what I can expect from submitting issues and/or PR's. If that is something you currently can't handle, it's not worth the hassle of reporting.

What do you think about collaboration and sharing the maintenance burden?`

**Comment by YetAnotherNerd** [comment]
Hi @JOJ0 ,
i don't do any active development right now, but i'll hit the merge button on some PRs that keep it running.
Since i don't use beets myself, fixes to the beets plugin are warmly welcome.
If you investigated on problems, feel free to share your insights - even unhandled issues/prs can hold information for some further development.

**Comment by arsaboo** [comment]
I was so looking forward to this plugin...but did not work for me. I think a basic clean-up to get it running would be a good start already. I have played a little bit with the `lastgenre` plugin and have a little idea about genres work.

**Comment by JOJ0** [comment]
Hi @arsaboo what exactly did not work? I use it occasionally and it works basically. If loading the beets plugin is the problem. I have this in my config to make beets find it:

```
pluginpath:
    - ~/git/whatlastgenre/plugin/beets/beetsplug
```

That said, it's a cool plugin yes, but two caveats that make it a only a second choice option (after lastgenre) for my personal use cases are (IIRC):

- Various artists handling does not work properly (as mentioned already in my initial post).
- The plugin is only working on an album basis - that is the most problem for my usecase - As a DJ I vouche for any track should have the right for its own genre :-)

That is why I still use lastgenre and use this plugin as a backup when lastgenre doesnt find anything.

Hope that helps and doesn't reduce your motivation to maybe submit some fixes to this wonderful plugin.

Thanks @YetAnotherNerd for your reply back then, I realise that I never anwered. Sorry! Still appreciate your work and your words! :)

**Comment by YetAnotherNerd** [comment]
> * Various artists handling does not work properly (as mentioned already in my initial post).

Never seen any details to this.


> * The plugin is only working on an album basis - that is the most problem for my usecase - As a DJ I vouche for any track should have the right for its own genre :-)

Not doing track scope is a conscious design decision of the early days of whatlastgenre. There was the idea to individually tag tracks to identify and distinguish specific tracks (eg. ballads) inside an album. However, one key feature of wlg is to find the "right" genres by asking many and build consent, not by "guessing" exceptions and specifics. Doing additional web requests for each track has massive performance impact not to be underestimated - for hardly no additional benefits. (I did research on this in the past, results lost with wcd forums.)

I understand your wish for tagging genres to just a bunch of tracks, but whatlastgenre was never meant to do this and for the reasons above i decided against mutt-albums back in the day. (Now they appeared again - happy birthday mutt-albums! :)
If you wanna fix your tracks, just copy the code around the way you need it and have it done. If you end up with reasonable mutt album support on the way, feel free to share it.

**Comment by JOJ0** [comment]
> > * Various artists handling does not work properly (as mentioned already in my initial post).

> Never seen any details to this.
> 
Yeah so sorry for not providing them back when I found out. Only with beets plug, standalone worked fine.


As for the rest: thanks for clarifying, I figured it was a design decision and most of all not easy. For now I'm taking some ideas/code and quickfix things in the beets lastgenre plugin I find unbearable (normalising genre spelling by regex and aliases as a first step), so thanks!! I will submit things into the foss world again at some point...

**Comment by arsaboo** [comment]
I feel like it may not be a bad idea to combine wlg and lastgenre plugins. I like the wlg implementation (to configure different sources that can be easily extended). I have added some fixes to the wlg plugin (canonicalization), but that was largely duplicating the lastgenre code. 

Right now, wlg only provides Discogs tags beyond the last genre plugin. If we can abstract the discord portion out, we can just extend the lastgenre plugin to include discord genres as well. Thoughts?

**Comment by JOJ0** [comment]
Hi, I renamed this thread since I found the original name I chose a little misleading and negative sounding. Hope that is ok !
